name = "NonSmoothDynamics"
uuid = "8d87df4a-0602-5753-9075-02367bcbd96d"
authors = ["Tangi Migot <tangi.migot@gmail.com>"]
version = "0.1.0"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.10"
